apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp-service

spec:
  selector:
    app: {{ .Release.Name }}-webapp
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port}}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      

      
   
